### ISSUE TITLE
Add npm shrinkwrap

### ISSUE THREAD

**Issue by phildotdev** [Akuda/fedkit#31]
Lets lock the dependences if we have tested they are working.

**Comment by PJL101** [comment]
This isn't needed as we are using bower for frontend management.

**Comment by phildotdev** [comment]
This has been reopened as it is a real world problem. Libsass has just changed version unexpectedly on a project.

**Comment by phildotdev** [comment]
Moved to https://github.com/PJL101/fedkit/issues/4
